# Special LDC compiler definitions

set(CMAKE_D_VERBOSE_FLAG "-v")
set(CMAKE_D_COMPILE_OPTIONS_PIC "-fPIC")

set(CMAKE_D_FLAGS_INIT "")
set(CMAKE_D_FLAGS_DEBUG_INIT "-g")
set(CMAKE_D_FLAGS_RELEASE_INIT "-O3 -release")
set(CMAKE_D_FLAGS_MINSIZEREL_INIT "-Os -release")
set(CMAKE_D_FLAGS_RELWITHDEBINFO_INIT "-O1 -g -release")
set(CMAKE_D_CREATE_ASSEMBLY_SOURCE    "<CMAKE_D_COMPILER> <DEFINES> <FLAGS> <SOURCE> -c -output-s -of<ASSEMBLY_SOURCE>")

set(CMAKE_SHARED_LIBRARY_D_FLAGS "-fPIC")
set(CMAKE_SHARED_LIBRARY_CREATE_D_FLAGS "-shared")
